/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "matrix_Op.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

matrix *
add_1(data1 *argp, CLIENT *clnt)
{
	static matrix clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ADD,
		(xdrproc_t) xdr_data1, (caddr_t) argp,
		(xdrproc_t) xdr_matrix, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

matrix *
mul_1(data1 *argp, CLIENT *clnt)
{
	static matrix clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MUL,
		(xdrproc_t) xdr_data1, (caddr_t) argp,
		(xdrproc_t) xdr_matrix, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

matrix *
inv_1(data2 *argp, CLIENT *clnt)
{
	static matrix clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, INV,
		(xdrproc_t) xdr_data2, (caddr_t) argp,
		(xdrproc_t) xdr_matrix, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

matrix *
tra_1(data2 *argp, CLIENT *clnt)
{
	static matrix clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, TRA,
		(xdrproc_t) xdr_data2, (caddr_t) argp,
		(xdrproc_t) xdr_matrix, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
