/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MATRIX_OP_H_RPCGEN
#define _MATRIX_OP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define sz 50

struct matrix {
	int row;
	int col;
	struct {
		u_int mat_len;
		double *mat_val;
	} mat;
};
typedef struct matrix matrix;


struct data1 {
	matrix A;
	matrix B;
	char operator;
};
typedef struct data1 data1;

struct data2 {
	matrix A;
	char operator;
};
typedef struct data2 data2;

#define CALCULATE_PROG 0x2fffffff
#define CALCULATE_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  matrix * add_1(data1 *, CLIENT *);
extern  matrix * add_1_svc(data1 *, struct svc_req *);
#define MUL 2
extern  matrix * mul_1(data1 *, CLIENT *);
extern  matrix * mul_1_svc(data1 *, struct svc_req *);
#define INV 3
extern  matrix * inv_1(data2 *, CLIENT *);
extern  matrix * inv_1_svc(data2 *, struct svc_req *);
#define TRA 4
extern  matrix * tra_1(data2 *, CLIENT *);
extern  matrix * tra_1_svc(data2 *, struct svc_req *);
extern int calculate_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  matrix * add_1();
extern  matrix * add_1_svc();
#define MUL 2
extern  matrix * mul_1();
extern  matrix * mul_1_svc();
#define INV 3
extern  matrix * inv_1();
extern  matrix * inv_1_svc();
#define TRA 4
extern  matrix * tra_1();
extern  matrix * tra_1_svc();
extern int calculate_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_matrix (XDR *, matrix*);
extern  bool_t xdr_matrix (XDR *, matrix*);
extern  bool_t xdr_data1 (XDR *, data1*);
extern  bool_t xdr_data2 (XDR *, data2*);

#else /* K&R C */
extern bool_t xdr_matrix ();
extern bool_t xdr_matrix ();
extern bool_t xdr_data1 ();
extern bool_t xdr_data2 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MATRIX_OP_H_RPCGEN */
